---
  # Configuration sample file for Djinko (YAML)
  application:
    title: "djinko"
    repository: "/home/arkub/git/djinko.data/data-1/"
    docSubdir: ""
    remote: ""
    pushInterval: 30
    secret: "lksjdfada0010101DNNQSDKdd27?2101"
  server:
    hostname: "umxdev.com"
    port: 8000
    localOnly: false
    baseUrl: "http://umxdev.com:8000"
  authorization:
    anonRead: true
    validMatches: ".+"
  authentication:
    google:
      enabled: true
    twitter:
      enabled: true
      oauthkeys:
        consumerKey : 'fytCW2YVtV3QYClAIV8vA'
        consumerSecret : 'dnXAumqDkGr5p3gKm9CIC4EPbaV5OkWPpDYU2xVNg'
    facebook:
      enabled: true
      oauthkeys:
        clientID : '491166480975374'
        clientSecret : 'cd05173cecc60189b5ad96bc18dce6b3'
    alone:
      enabled: true
      username: "arkub"
      passwordHash: "63c1c7896a0588291c41c50087a7e1b9fe2124ed"
      email: "slauriere@ubimix.com"
  accessRules:
    - roles: [ "admin", "owner" ]
      allows:
        - resources: ["api", "resources"]
          permissions: [ "get", "put", "delete" ]
    - roles: ["guest"]
      allows:
        - resources: "wiki"
          permissions:  ["get"]
  userRoles:
     Anonymous: [ "guest" ]
     Stéphane Laurière: [ "admin" ]
     arkub: [ "admin" ]
     Mikhail Kotelnikov: [ "admin" ]
     Loïc Haÿ: ["admin"]
  twitterClient:
        consumerKey : 'fytCW2YVtV3QYClAIV8vA'
        consumerSecret : 'dnXAumqDkGr5p3gKm9CIC4EPbaV5OkWPpDYU2xVNg'
        accessTokenKey : '10078002-PlycJAuvnnRfhNyPQBxwIyqvnhHYAHOSTFHngi1ow'
        accessTokenSecret : '3zqJDH51aCuZxrhMnEmLjrmQPkUPxij0GB0oF3UM'
