---
# Configuration sample file (YAML)
application:
    title: "Djk"
baasbox:
    host: "http://localhost:9000"
    username: 
    password: ''
    appcode: 1234567890
dataSources:
    - source: '/home/arkub/git/cci-preference-commerce/data/commerces-20140707.geo.json'
      collection: 'commerces'

