---
# Configuration sample file (YAML)
application:
    title: "Djk"
baasbox:
    host: "http://localhost:9000"
    username: arkub
    password: '[leliendéfait]'
    appcode: 1234567890
dataSources:
    - source: '/home/arkub/git/cci-preference-commerce/data/commerces060514.geo.json'
      collection: 'commerces'

